
post http://localhost:3000/api/v1/cares
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFmMDg3MDM3YWEwODY2ZWM5OGMzMDAiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGNhIiwiaWF0IjoxNzEzNTUwMjEwLCJleHAiOjE3MTM2MzY2MTB9.F-UbKVK62xHOQgMWYoUQc8J2r_cRjGXApLQzZRnlfLU

{
  "services": ["661eb60c79fa6d69a77c6cb2","66218eb79daa9a2616fde204"],
  "pet": "661f040ad6423995b91ceaed",
  "hours": 6,
  "description": "a ver esta otra"
}

###

PATCH  http://localhost:3000/api/v1/cares/6622b4bb455d41f9ee5d15ba
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjIxZTNjNWI5ZGZhNWYwMDBkZjQyZDciLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM5IiwiaWF0IjoxNzEzNTUxNTE2LCJleHAiOjE3MTM2Mzc5MTZ9.jOwrasE8yGidEcvUu3CgOw0B2eMQPy7J0MzrWZfF7bY

{
  "status": "accept"
}

###

get http://localhost:3000/api/v1/cares
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzNTUwNzEwLCJleHAiOjE3MTM2MzcxMTB9.nWCWSILzWpUjtRdWF2tfcEreR8vrVhUAs2LVJEVd8c8

###

get http://localhost:3000/api/v1/cares/6622b40c455d41f9ee5d15b8
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzNTUwNzEwLCJleHAiOjE3MTM2MzcxMTB9.nWCWSILzWpUjtRdWF2tfcEreR8vrVhUAs2LVJEVd8c8

###

get http://localhost:3000/api/v1/cares/caretaker/6621e4b6b9dfa5f000df42e1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjIxZTNjNWI5ZGZhNWYwMDBkZjQyZDciLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM5IiwiaWF0IjoxNzEzNTUxNTE2LCJleHAiOjE3MTM2Mzc5MTZ9.jOwrasE8yGidEcvUu3CgOw0B2eMQPy7J0MzrWZfF7bY

###

delete  http://localhost:3000/api/v1/cares/661f0ad582ca145641b3718b
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWU4MzE4NzM0YWFlMzc1NjUwZWYiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGNhIiwiaWF0IjoxNzEzMjg3OTE2LCJleHAiOjE3MTMzNzQzMTZ9.YC9xcGx8HKg_2BLHP095YiADFKVBUL9B74ahiLpttgY


