post http://localhost:3000/api/v1/pets
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzMzA4NTM0LCJleHAiOjE3MTMzOTQ5MzR9.-JMBCfr1cor7aCSQFVSGxO6O4pYEyMSDWV4E78lNnp0

{
  "name": "rinoceronte"
}

###
get http://localhost:3000/api/v1/pets

###
get http://localhost:3000/api/v1/pets/661eaf4a18734aae375650f4

###
patch http://localhost:3000/api/v1/pets/661eaf4a18734aae375650f4
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzMzA4NTM0LCJleHAiOjE3MTMzOTQ5MzR9.-JMBCfr1cor7aCSQFVSGxO6O4pYEyMSDWV4E78lNnp0

{
  "name": "ave"
}

###
delete http://localhost:3000/api/v1/pets/661f03d3d6423995b91ceaea
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzMzA4NTM0LCJleHAiOjE3MTMzOTQ5MzR9.-JMBCfr1cor7aCSQFVSGxO6O4pYEyMSDWV4E78lNnp0

