post http://localhost:3000/api/v1/pets
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzNTQ3ODE3LCJleHAiOjE3MTM2MzQyMTd9.LXsIwgHzHs8N8TgDC5_x_SeYvVZ4KOxY8u59DtXTpOs

{
  "name": "vaca"
}

###
get http://localhost:3000/api/v1/pets

###
get http://localhost:3000/api/v1/pets/6622b084b5740bb841373bcc

###
patch http://localhost:3000/api/v1/pets/6622b084b5740bb841373bcc
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzNTQ3ODE3LCJleHAiOjE3MTM2MzQyMTd9.LXsIwgHzHs8N8TgDC5_x_SeYvVZ4KOxY8u59DtXTpOs

{
  "name": "vaquita"
}

###
delete http://localhost:3000/api/v1/pets/6622b084b5740bb841373bcc
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFlYWFiMWI1YmUyMzFmNzllZTFkMDEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM4IiwiaWF0IjoxNzEzNTQ3ODE3LCJleHAiOjE3MTM2MzQyMTd9.LXsIwgHzHs8N8TgDC5_x_SeYvVZ4KOxY8u59DtXTpOs


