post http://localhost:3000/api/v1/auth/login
content-type: application/json

{
"username": "admin",
"password": "admin@123"
}

###

post http://localhost:3000/api/v1/auth/register
content-type: application/json

{
"role": "66157d1e7aff6b63452074c9",
"first_name": "caretaker",
"last_name": "caretaker",
"email": "caretaker@hotmail.com",
"password": "Admin@123"
}

###
post http://localhost:3000/api/v1/caretakers
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFmMDdlODM3YWEwODY2ZWM5OGMyZmEiLCJyb2xlIjoiNjYxNTdkMWU3YWZmNmI2MzQ1MjA3NGM5IiwiaWF0IjoxNzEzMzExMDM3LCJleHAiOjE3MTMzOTc0Mzd9.0GsSJzgm_r17vcokhJt68vLnBIPJBORGA_9lrsHCV_4

{
  "services": [],
  "pets": [],
  "status": "44a",
  "active_requests": 2,
  "description": "String"
}

###

post http://localhost:3000/api/v1/auth/register
content-type: application/json

{
"role": "66157d1e7aff6b63452074ca",
"first_name": "client",
"last_name": "client",
"email": "clientr@hotmail.com",
"password": "Admin@123"
}

###

post http://localhost:3000/api/v1/auth/login
content-type: application/json

{
"username": "client1713309808567",
"password": "Admin@123"
}

###

post http://localhost:3000/api/v1/auth/login
content-type: application/json

{
"username": "caretaker1713309672116",
"password": "Admin@123"
}